--------------------------------------------------------
--  SECUENCIA
--------------------------------------------------------
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_IDUSUARIO', 5);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_IDSECCION', 5);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_IDSOCIO', 105);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_IDEVENTO', 2);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_IDPAGOEVENTO', 3);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_NOTEVENTO', 6);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_IDCUOTA', 2);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_IDPAGOCUOTA', 4);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_DOCUMENTO', 2);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_NOTDOCUMENTO', 1);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_TRANSACCION', 3);
INSERT INTO APP."SEQUENCE" (SEQ_NAME, SEQ_COUNT) VALUES ('S_ENTCALENDARIO', 5);

--------------------------------------------------------
--  USUARIOS
--------------------------------------------------------
INSERT INTO APP.USUARIO (ID_USUARIO, DTYPE, EMAIL, PASS, PERFIL) VALUES (1, 'S', 'admin@correo.com', 'root', 'ROOT');
INSERT INTO APP.USUARIO (ID_USUARIO, DTYPE, EMAIL, PASS, PERFIL) VALUES (2, 'S', 'scouter@correo.com', 'oye', 'SCOUT');
INSERT INTO APP.USUARIO (ID_USUARIO, DTYPE, EMAIL, PASS, PERFIL) VALUES (3, 'S', 'edu@correo.com', '1234', 'EDUCANDO');
INSERT INTO APP.USUARIO (ID_USUARIO, DTYPE, EMAIL, PASS, PERFIL) VALUES (4, 'S', 'HansTheBoy@correo.com', '1234', 'EDUCANDO');
INSERT INTO APP.USUARIO (ID_USUARIO, DTYPE, EMAIL, PASS, PERFIL) VALUES (5, 'S', 'LolaSol@correo.com', '1234', 'EDUCANDO');

--------------------------------------------------------
--  SECCIONES
--------------------------------------------------------
INSERT INTO APP.SECCION (ID_SECCION, DESCRIPCION, EDAD_MAX, EDAD_MIN, NOMBRE) VALUES (0, 'Seccion de administracion', 100, 0, 'Administracion');
INSERT INTO APP.SECCION (ID_SECCION, DESCRIPCION, EDAD_MAX, EDAD_MIN, NOMBRE) VALUES (1, 'Esta es la seccion de los Castores.', 8, 6, 'Castores');
INSERT INTO APP.SECCION (ID_SECCION, DESCRIPCION, EDAD_MAX, EDAD_MIN, NOMBRE) VALUES (2, 'Esta es la seccion de la Manada.', 11, 8, 'Manada');
INSERT INTO APP.SECCION (ID_SECCION, DESCRIPCION, EDAD_MAX, EDAD_MIN, NOMBRE) VALUES (3, 'Esta es la seccion de la Tropa.', 14, 11, 'Tropa');
INSERT INTO APP.SECCION (ID_SECCION, DESCRIPCION, EDAD_MAX, EDAD_MIN, NOMBRE) VALUES (4, 'Esta es la seccion de la Unidad.', 17, 14, 'Unidad');
INSERT INTO APP.SECCION (ID_SECCION, DESCRIPCION, EDAD_MAX, EDAD_MIN, NOMBRE) VALUES (5, 'Esta es la seccion del Clan.', 21, 17, 'Clan');

--------------------------------------------------------
--  SOCIOS
--------------------------------------------------------
INSERT INTO APP.SOCIO (ID_USUARIO, AMBITO, APELLIDOS, CARGO, DIRECCION, DNI, FECHA_BAJA, FECHA_FIRMA, FECHA_INGRESO, FECHA_NACIMIENTO, GRUPO, ID_SOCIO, INFO_TUTORES, NOMBRE, SEXO, TELEFONO, TELEFONO_MOVIL, SECCION_ID_SECCION) VALUES (1, 'Federal', 'Rana', 'Administrador', 'Calle de Atras, N1, 1A', '00000001A', null, '2018-05-31', '2018-05-31', '1994-02-13', 'Clan', 101, NULL, 'Gustavo', 'Hombre', 952000001, 650000001, 0);
INSERT INTO APP.SOCIO (ID_USUARIO, AMBITO, APELLIDOS, CARGO, DIRECCION, DNI, FECHA_BAJA, FECHA_FIRMA, FECHA_INGRESO, FECHA_NACIMIENTO, GRUPO, ID_SOCIO, INFO_TUTORES, NOMBRE, SEXO, TELEFONO, TELEFONO_MOVIL, SECCION_ID_SECCION) VALUES (2, 'Federal', 'Fernandez', 'Instructor', 'Calle de Atras, N1, 1B', '12345678D', null, '2018-05-31', '2018-05-31', '1994-02-13', 'Clan', 102, NULL, 'Juan', 'Hombre', 952121212, 650123456, 5);
INSERT INTO APP.SOCIO (ID_USUARIO, AMBITO, APELLIDOS, CARGO, DIRECCION, DNI, FECHA_BAJA, FECHA_FIRMA, FECHA_INGRESO, FECHA_NACIMIENTO, GRUPO, ID_SOCIO, INFO_TUTORES, NOMBRE, SEXO, TELEFONO, TELEFONO_MOVIL, SECCION_ID_SECCION) VALUES (3, 'Grupo', 'Educado', '', 'Calle de Atras, N1, 2A.', '11111111V', null, '2018-05-31', '2018-05-31', '1998-07-19', 'Clan', 103, NULL, 'Eduardo', 'Hombre', 952111111, 650111111, 5);
INSERT INTO APP.SOCIO (ID_USUARIO, AMBITO, APELLIDOS, CARGO, DIRECCION, DNI, FECHA_BAJA, FECHA_FIRMA, FECHA_INGRESO, FECHA_NACIMIENTO, GRUPO, ID_SOCIO, INFO_TUTORES, NOMBRE, SEXO, TELEFONO, TELEFONO_MOVIL, SECCION_ID_SECCION) VALUES (4, 'Grupo', 'Topo', '', 'Calle de Atras, N1, 2B', '22222222P', null, '2018-05-31', '2018-05-31', '1997-02-27', 'Clan', 104, NULL, 'Hans', 'Hombre', 952222222, 650222222, 5);
INSERT INTO APP.SOCIO (ID_USUARIO, AMBITO, APELLIDOS, CARGO, DIRECCION, DNI, FECHA_BAJA, FECHA_FIRMA, FECHA_INGRESO, FECHA_NACIMIENTO, GRUPO, ID_SOCIO, INFO_TUTORES, NOMBRE, SEXO, TELEFONO, TELEFONO_MOVIL, SECCION_ID_SECCION) VALUES (5, 'Grupo', 'Sol', '', 'Calle de Atras, N1, 2C.', '33333333C', null, '2018-05-31', '2018-05-31', '1998-04-02', 'Clan', 105, NULL, 'Lola', 'Mujer', 952333333, 650333333, 5);

--------------------------------------------------------
--  EVENTOS
--------------------------------------------------------
INSERT INTO APP.EVENTO (ID_EVENTO, DESCRIPCION, FECHA, IMAGEN, LOCALIZACION, NOMBRE, PRECIO, SECCION_ID_SECCION) VALUES (1, 'Evento para ir a pescar al lago.', '2018-06-15', 'resources/images/pesca.jpg', 'Torremolinos', 'Pesca en Torremolinos', 17.99, 5);
INSERT INTO APP.EVENTO (ID_EVENTO, DESCRIPCION, FECHA, IMAGEN, LOCALIZACION, NOMBRE, PRECIO, SECCION_ID_SECCION) VALUES (2, 'Ruta de senderismo por Jarapalo.', '2018-07-09', 'resources/images/montana.jpg', 'Alhaurin de la Torre', 'Senderismo por Jarapalo', 5.0, 5);

--------------------------------------------------------
--  INSCRIPCION
--------------------------------------------------------
INSERT INTO APP.INSCRIPCION (INSCRIPCION_EVENTO_FK, INSCRIPCION_SOCIO_FK) VALUES (1, 3);
INSERT INTO APP.INSCRIPCION (INSCRIPCION_EVENTO_FK, INSCRIPCION_SOCIO_FK) VALUES (1, 5);
INSERT INTO APP.INSCRIPCION (INSCRIPCION_EVENTO_FK, INSCRIPCION_SOCIO_FK) VALUES (2, 3);

--------------------------------------------------------
--  ASISTENCIA
--------------------------------------------------------
INSERT INTO APP.ASISTENCIA (ASISTENCIA_EVENTO_FK, ASISTENCIA_SOCIO_FK) VALUES (1, 3);
INSERT INTO APP.ASISTENCIA (ASISTENCIA_EVENTO_FK, ASISTENCIA_SOCIO_FK) VALUES (1, 5);
INSERT INTO APP.ASISTENCIA (ASISTENCIA_EVENTO_FK, ASISTENCIA_SOCIO_FK) VALUES (2, 3);


--------------------------------------------------------
--  PAGO_EVENTO
--------------------------------------------------------
INSERT INTO APP.PAGO_EVENTO (ID_PAGO, FECHA, IMPORTE, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (1, '2018-05-29', 17.99, 1, 3);
INSERT INTO APP.PAGO_EVENTO (ID_PAGO, FECHA, IMPORTE, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (2, '2018-05-31', 17.99, 1, 5);
INSERT INTO APP.PAGO_EVENTO (ID_PAGO, FECHA, IMPORTE, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (3, '2018-05-31', 5.0, 2, 3);

--------------------------------------------------------
--  NOTIFICACION_EVENTO
--------------------------------------------------------
INSERT INTO APP.NOTIFICACION_EVENTO (ID_NOT_EVENTO, ESTADO, FECHANOTIFICACION, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (1, 'True', '2018-05-12', 1, 3);
INSERT INTO APP.NOTIFICACION_EVENTO (ID_NOT_EVENTO, ESTADO, FECHANOTIFICACION, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (2, 'False', '2018-05-12', 1, 4);
INSERT INTO APP.NOTIFICACION_EVENTO (ID_NOT_EVENTO, ESTADO, FECHANOTIFICACION, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (3, 'True', '2018-05-12', 1, 5);
INSERT INTO APP.NOTIFICACION_EVENTO (ID_NOT_EVENTO, ESTADO, FECHANOTIFICACION, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (4, 'True', '2018-05-09', 2, 3);
INSERT INTO APP.NOTIFICACION_EVENTO (ID_NOT_EVENTO, ESTADO, FECHANOTIFICACION, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (5, 'False', '2018-05-12', 2, 4);
INSERT INTO APP.NOTIFICACION_EVENTO (ID_NOT_EVENTO, ESTADO, FECHANOTIFICACION, EVENTO_ID_EVENTO, SOCIO_ID_USUARIO) VALUES (6, 'False', '2018-05-09', 2, 5);

--------------------------------------------------------
--  CUOTAS
--------------------------------------------------------
INSERT INTO APP.CUOTA (ID_CUOTA, DESCRIPCION, IMPORTE, NOMBRE) VALUES (1, 'Cuota anual para Educandos', 59.99, 'Educando');
INSERT INTO APP.CUOTA (ID_CUOTA, DESCRIPCION, IMPORTE, NOMBRE) VALUES (2, 'Cuota anual para Scouters', 29.99, 'Scouter');

--------------------------------------------------------
--  PAGO_CUOTA
--------------------------------------------------------
INSERT INTO APP.PAGO_CUOTA (ID_PAGO, FECHA, IMPORTE, CUOTA_ID_CUOTA, SOCIO_ID_USUARIO) VALUES (1, '2018-01-01', 29.99, 2, 2);
INSERT INTO APP.PAGO_CUOTA (ID_PAGO, FECHA, IMPORTE, CUOTA_ID_CUOTA, SOCIO_ID_USUARIO) VALUES (2, '2019-01-01', 59.99, 1, 3);
INSERT INTO APP.PAGO_CUOTA (ID_PAGO, FECHA, IMPORTE, CUOTA_ID_CUOTA, SOCIO_ID_USUARIO) VALUES (3, '2018-01-01', 59.99, 1, 4);
INSERT INTO APP.PAGO_CUOTA (ID_PAGO, FECHA, IMPORTE, CUOTA_ID_CUOTA, SOCIO_ID_USUARIO) VALUES (4, '2019-01-01', 59.99, 1, 5);

--------------------------------------------------------
--  DOCUMENTO
--------------------------------------------------------
INSERT INTO APP.DOCUMENTO (ID_DOCUMENTO, ENLACE, ESTADO, FECHA, NOMBRE, TIPO, SOCIO_ID_USUARIO) VALUES (1, './faces/resources/docs/578025.png', 'ENTREGADO', '2018-02-19', 'Alergias', '1', 4);
INSERT INTO APP.DOCUMENTO (ID_DOCUMENTO, ENLACE, ESTADO, FECHA, NOMBRE, TIPO, SOCIO_ID_USUARIO) VALUES (2, './faces/resources/docs/dni.pdf', 'ENTREGADO', '2018-05-17', 'DNI', '2', 5);

--------------------------------------------------------
--  NOTIFICACION_DOCUMENTO
--------------------------------------------------------
INSERT INTO APP.NOTIFICACION_DOCUMENTO (ID_NOT_DOCUMENTO, ESTADO, FECHANOTIFICACION, DOCUMENTO_ID_DOCUMENTO, SOCIO_ID_USUARIO) VALUES (1, 'True', '2018-05-12', 1, 1);

--------------------------------------------------------
--  TRANSACCION
--------------------------------------------------------
INSERT INTO APP.TRANSACCION (ID_TRANSACCION, CONCEPTO, FECHA, IMPORTE, SOCIO_ID_USUARIO) VALUES (1, 'Pago arreglos oficina', '2018-04-10', -210.99, 1);
INSERT INTO APP.TRANSACCION (ID_TRANSACCION, CONCEPTO, FECHA, IMPORTE, SOCIO_ID_USUARIO) VALUES (2, 'Donacion', '2018-03-07', 100.0, 2);
INSERT INTO APP.TRANSACCION (ID_TRANSACCION, CONCEPTO, FECHA, IMPORTE, SOCIO_ID_USUARIO) VALUES (3, 'Pago herramientas para eventos', '2018-05-11', -30.99, 1);

--------------------------------------------------------
--  ENTRADA_CALENDARIO
--------------------------------------------------------
INSERT INTO APP.ENTRADA_CALENDARIO (ID_ENTRADA_CALENDARIO, "CATEGORÍA", "DESCRIPCIÓN", FECHA, SOCIO_ID_USUARIO) VALUES (1, 'Ingreso', 'Te has unido al Grupo Scout 39 Santo �ngel.', '2018-05-31', 4);
INSERT INTO APP.ENTRADA_CALENDARIO (ID_ENTRADA_CALENDARIO, "CATEGORÍA", "DESCRIPCIÓN", FECHA, SOCIO_ID_USUARIO) VALUES (2, 'Evento', 'Evento para ir a pescar al lago.', '2018-05-31', 4);
INSERT INTO APP.ENTRADA_CALENDARIO (ID_ENTRADA_CALENDARIO, "CATEGORÍA", "DESCRIPCIÓN", FECHA, SOCIO_ID_USUARIO) VALUES (3, 'Evento', 'Evento para ir a pescar al lago.', '2018-05-31', 5);
INSERT INTO APP.ENTRADA_CALENDARIO (ID_ENTRADA_CALENDARIO, "CATEGORÍA", "DESCRIPCIÓN", FECHA, SOCIO_ID_USUARIO) VALUES (4, 'Insignia', 'Has conseguido la insignia de la valentia. Enhorabuena.', '2018-05-31', 3);
INSERT INTO APP.ENTRADA_CALENDARIO (ID_ENTRADA_CALENDARIO, "CATEGORÍA", "DESCRIPCIÓN", FECHA, SOCIO_ID_USUARIO) VALUES (5, 'Insignia', 'Has conseguido la insignia de la valentia. Enhorabuena.', '2018-05-31', 5);

